name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Set up dependencies
      uses: jdx/mise-action@v4
    - name: Set up environment
      run: mkdir cdk.tmp
      working-directory: backend
    - name: Set up test environment
      run: cp dummy.env .env
      working-directory: backend

    # the ordering is weird, because we're trying to get information about fundamental failures quicker - i.e. breadth-first not depth-first

    # get all deps
    - name: "get deps: root"
      run: pnpm ci
    - name: "get deps: shared"
      run: pnpm ci
      working-directory: shared
    - name: "get deps: data-prep"
      run: pnpm ci
      working-directory: data-prep
    - name: "get deps: backend"
      run: pnpm ci
      working-directory: backend
    - name: "get deps: UI"
      run: pnpm ci
      working-directory: ui

    # build
    - name: "build: backend"
      run: pnpm run testsynth
      working-directory: backend
    - name: "build: UI"
      run: pnpm run build
      working-directory: ui

    # test
    - name: "test: shared"
      run: pnpm run test
      working-directory: shared
    - name: "test: data-prep"
      run: pnpm run test
      working-directory: data-prep
    - name: "test: backend"
      run: pnpm run test
      working-directory: backend
    - name: "test: UI"
      run: pnpm run test
      working-directory: ui
